# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Edbctl < Formula
  desc "EnterpriseDB HM edbctl CLI Tool"
  homepage "https://github.com/EnterpriseDB/homebrew-tap"
  version "1.8.1"

  depends_on "libpq"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://downloads.enterprisedb.com/public/homebrew-edb/raw/versions/1.8.1-1/edbctl_1.8.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
    sha256 "8a28a6e09e755e91e5df19bffc649b9dc6f7fe9f9bcb02c69a3f541409615547"

    define_method(:install) do
      bin.install "edbctl"
    end
  end
  if Hardware::CPU.arm?
    url "https://downloads.enterprisedb.com/public/homebrew-edb/raw/versions/1.8.1-1/edbctl_1.8.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
    sha256 "adf434e7e32afcc3ded7e935a44ffc3d251169bc82c9f8a69dcfae8544cdfc53"

    define_method(:install) do
      bin.install "edbctl"
    end
  end
end
